apiVersion: v1
data:
  game.properties: |
    enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
    secret.code.passphrase=UUDDLRLRBABAS
    secret.code.allowed=true
    secret.code.lives=30    
    somethinghere = somethingtest
kind: ConfigMap
metadata:
  name: austin-config
  namespace: austin-spin-ftw
